Support more detailed dynamic build arguments
We can now have dynamically-defined build arguments based on the variant and revision, with the following precedence (highest-to-lowest):

    1. specific matrix variant and specific matrix revision
    2. all matrix variants for a specific matrix revision
    3. specific matrix variant for all matrix revisions
    4. all matrix variants for all matrix revisions

This allows re-use, and avoids silly re-definitions.

diff --git a/.github/workflows/ecr-publish.yml b/.github/workflows/ecr-publish.yml
--- a/.github/workflows/ecr-publish.yml
+++ b/.github/workflows/ecr-publish.yml
@@ -319,49 +319,66 @@ jobs:
           echo "export VARIANT=${MATRIX_VARIANT@Q}" >> .env
           echo "VARIANT=${MATRIX_VARIANT@Q}"
 
-          REVISION_SUFFIX=""
-          [ "${MATRIX_REVISION}" == "*" ] || REVISION_SUFFIX="-${MATRIX_REVISION}"
+          [ "${MATRIX_REVISION}" == "*" ] && REVISION_SUFFIX="all" || REVISION_SUFFIX="${MATRIX_REVISION}"
 
           # See if we have a revision-specific file with build arguments to provide
-          ARGS_DIR="${GITHUB_WORKSPACE}/.args"
-          SCRIPT_NAME="${VARIANT}/dynamic${REVISION_SUFFIX}"
-          SCRIPT="${ARGS_DIR}/${SCRIPT_NAME}"
-          FILE_NAME="${VARIANT}/static${REVISION_SUFFIX}"
-          FILE="${ARGS_DIR}/${FILE_NAME}"
 
-          BUILD_ARGS=""
-          RC=0
-          if [ -f "${SCRIPT}" ] ; then
-              if [ -x "${SCRIPT}" ] ; then
-                  echo -e "ERROR: The build arguments script [${SCRIPT_NAME}] is not executable"
-                  exit 1
-              fi
-              BUILD_ARGS="$( "${SCRIPT}" )" || RC=${?}
-              if [ ${RC} -ne 0 ] ; then
-                  echo -e "ERROR: Failed to compute the build arguments from [${SCRIPT_NAME}] (rc=${RC}): ${BUILD_ARGS}"
-                  exit 1
-              fi
-              echo -e "The script [${SCRIPT_NAME}] produced the following (raw) build arguments:"
-              echo -e "--------------------------------------------------------------------------------"
-              echo -e "${BUILD_ARGS}"
-              echo -e "--------------------------------------------------------------------------------"
-          elif [ -f "${FILE}" ] ; then
-              if [ -x "${FILE}" ] ; then
-                  echo -e "ERROR: The build arguments file [${FILE_NAME}] is not readable"
-                  exit 1
-              fi
-              BUILD_ARGS="$(<"${FILE}")" || RC=${?}
-              if [ ${RC} -ne 0 ] ; then
-                  echo -e "ERROR: Failed to read the build arguments from [${FILE_NAME}] (rc=${RC})"
-                  exit 1
-              fi
-              echo -e "The file [${FILE_NAME}] produced the following (raw) build arguments:"
-              echo -e "--------------------------------------------------------------------------------"
-              echo -e "${BUILD_ARGS}"
-              echo -e "--------------------------------------------------------------------------------"
-          fi
+          # By processing the candidates in a specific order we can add precedence
+          # because later-defined arguments will override earlier-defined ones
+          CANDIDATES=(
+              "all/all"
+              "${VARIANT}/all"
+          )
+          [ -n "${REVISION_SUFFIX}" ] && CANDIDATES+=( "all/${REVISION_SUFFIX}" "${VARIANT}/${REVISION_SUFFIX}" )
 
-          if [ -n "${BUILD_ARGS}" ] ; then
+          ARGS_TEMP="$(mktemp --tmpdir="$(readlink -f .)" ".build-args-XXXXXX.tmp")"
+          ARGS_DIR="${GITHUB_WORKSPACE}/.build-args"
+          for CANDIDATE in "${CANDIDATES[@]}" ; do
+              [[ "${CANDIDATE}" =~ ^(.*)/(.*)$ ]] || continue
+
+              VARIANT="${BASH_REMATCH[1]}"
+              REVISION_SUFFIX="${BASH_REMATCH[2]}"
+
+              SCRIPT_NAME="${VARIANT}/dynamic-${REVISION_SUFFIX}"
+              SCRIPT="${ARGS_DIR}/${SCRIPT_NAME}"
+
+              FILE_NAME="${VARIANT}/static-${REVISION_SUFFIX}"
+              FILE="${ARGS_DIR}/${FILE_NAME}"
+
+              BUILD_ARGS=""
+              RC=0
+              if [ -f "${SCRIPT}" ] ; then
+                  if [ -x "${SCRIPT}" ] ; then
+                      echo -e "ERROR: The build arguments script [${SCRIPT_NAME}] is not executable"
+                      exit 1
+                  fi
+                  BUILD_ARGS="$( "${SCRIPT}" )" || RC=${?}
+                  if [ ${RC} -ne 0 ] ; then
+                      echo -e "ERROR: Failed to compute the build arguments from [${SCRIPT_NAME}] (rc=${RC}): ${BUILD_ARGS}"
+                      exit 1
+                  fi
+                  echo -e "The script [${SCRIPT_NAME}] produced the following (raw) build arguments:"
+                  echo -e "--------------------------------------------------------------------------------"
+                  echo -e "${BUILD_ARGS}"
+                  echo -e "--------------------------------------------------------------------------------"
+              elif [ -f "${FILE}" ] ; then
+                  if [ -x "${FILE}" ] ; then
+                      echo -e "ERROR: The build arguments file [${FILE_NAME}] is not readable"
+                      exit 1
+                  fi
+                  BUILD_ARGS="$(<"${FILE}")" || RC=${?}
+                  if [ ${RC} -ne 0 ] ; then
+                      echo -e "ERROR: Failed to read the build arguments from [${FILE_NAME}] (rc=${RC})"
+                      exit 1
+                  fi
+                  echo -e "The file [${FILE_NAME}] produced the following (raw) build arguments:"
+                  echo -e "--------------------------------------------------------------------------------"
+                  echo -e "${BUILD_ARGS}"
+                  echo -e "--------------------------------------------------------------------------------"
+              else
+                  continue
+              fi
+
               # The output must be a list of key-value pairs. Each key will be renamed
               # as BUILD_ARG_${KEY} and will be set as a build argument via docker's
               # --build-arg ${KEY}=${VALUE} mechanism.
@@ -369,10 +386,17 @@ jobs:
                   [[ "${VAR}" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*(.*)[[:space:]]*$ ]] || continue
                   KEY="${BASH_REMATCH[1]}"
                   VALUE="${BASH_REMATCH[2]}"
-                  echo "export BUILD_ARG_${KEY}=${VALUE@Q}" >> .env
                   echo "BUILD_ARG_${KEY}=${VALUE@Q}"
               done <<< "${BUILD_ARGS}"
-          fi
+          done > "${ARGS_TEMP}"
+
+          # Now we output the variables, only keeping the last definition
+          while read VAR ; do
+              VAL="$(grep "^${VAR}=" "${ARGS_TEMP}" | tail -1)"
+              echo "export ${VAL}" >> .env
+              echo "${VAL}"
+          done < <( sed -e 's;=.*$;;g' < "${ARGS_TEMP}" | sort -u )
+          rm -rf "${ARGS_TEMP}"
 
       - name: Docker Login to Alfresco Quay.IO (if applicable)
         env:
